### PR TITLE
Added BG images with higher resolution

### PR DESCRIPTION
**Pull request by shimmer12**
added rich quality background images

Screenshot 2023-10-06 170426
to this 
loginPage-bg1

and

Screenshot 2023-10-06 173032
to
Screenshot 2023-10-06 173046

### CODE REVIEW

**Comment by shimmer12** [comment]
kindly merge under hacktoberfest 2023 label

**Comment by rohitagr0310** [comment]
i checked the deployment log and the error is because of eslint 
please run 
`yarn eslint . --fix` in the root terminal and commit the changes

**Comment by shimmer12** [comment]
Hi there, its written invalid tag,is there any issue with that ?

**Comment by rohitagr0310** [comment]
There has been a major change in the home page, so the requirements for images is no more

**Comment by shimmer12** [comment]
okay thanks for stating reason, you can ping me if you are assugning any issues

**Comment by rohitagr0310** [comment]
@shimmer12 
Thank you for your understanding, since the home page is done, we will start working on student panel and admin panel. 

If you still are open to contribute, you can greatly help in that part

**Pull request closed without merging**
