### PR TITLE
Width of content

### PR DESCRIPTION
**Pull request by Vatsalmadhur**
Changed the width of content on the Home page.
Here is what it looks like now:
Screenshot 2023-10-05 at 1 10 18 AM
Screenshot 2023-10-05 at 1 10 43 AM

### CODE REVIEW

**Comment by rohitagr0310** [comment]
the text has become too small, it disturbs with the user experience

**Comment by Vatsalmadhur** [comment]
Okay so should i increase the font size or the overall width?

**Comment by rohitagr0310** [comment]
Increase the font size

**Comment by Vatsalmadhur** [comment]
I have made a fresh PR #276  with the branch name "widthOfContent2". Font size looks good to me now. Please have a look @rohitagr0310 and others.

In case of any other bugs, please quote me.

**Comment by rohitagr0310** [comment]
I have merged that pr

**Pull request closed without merging**
