### PR TITLE
Fix mobile first responsiveness #220

### LINKED ISSUE #220: Single column layout for mobile screens
The two column layout should shift to one column layout on mobile screens. 

Solution:
Implement grid layout for it that will switch  to single column on mobile screen.

### PR DESCRIPTION
**Pull request by ashishk1331**
In dev screenshot of resolved issue,

image

### CODE REVIEW

**Comment by ashishk1331** [comment]
@jain-anshika @jayesh2474 The checks failed. Can you review the PR?

**Comment by jain-anshika** [comment]
@ashishk1331  There are some issues and we are fixing it! We will review and merge your PR soon!!

**Comment by rohitagr0310** [comment]
@ashishk1331 
It seams that you add new packages in the package.json file which has installed node-gyp as an optional package which always causes problem with the deployment.

To address issue I ask of you to remove all the node-gyp installation that is present in the yarn.lock file

May I also know what packages did you add into the package.json file

**Comment by ashishk1331** [comment]
Okay. I'll remove the lock files and try again. The dependencies were legacy old and npm threw an error. So I forced installed all.

**Review by rohitagr0310 — APPROVED** [review]

**Comment by rohitagr0310** [comment]
Since the deployment works and the checks have all passed, I will merge it

Thank you for your contribution

**Comment by ashishk1331** [comment]
Yes sir. Thank you.

**Pull request merged**
