### PR TITLE
fix: Changed bg color to be consistent #226

### PR DESCRIPTION
**Pull request by RoastedBrotato**
The text color was already fixed in the latest version despite the task being assigned to me. I still changed the background color on hover to be consistent with the footer.

### CODE REVIEW

**Comment by qaidjoharj53** [comment]
All the PRs must be merged to develop branch only

**Comment by RoastedBrotato** [comment]
I am sorry but I'm confused, do I need to do the changes again and create a new pull request to the develop branch?

**Comment by rohitagr0310** [comment]
As soon as the pr is reviewed by the mainteners, the pr will be merged

Thank you for your contribution

**Comment by qaidjoharj53** [comment]
Your code creates conflicts in the deployment.
In yarn.lock file, at line 17857, It creates a dependency of `unixdgram`, which further creates errors in deployment.
Therefore, I am closing this Pull Request.
You may re-create a PR.

**Pull request closed without merging**
